packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  argon2: true
  better-sqlite3: true
  electron: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  prisma: true
